### ISSUE TITLE
Ajout de potentiels remplaçant lors de la création d'une équipe tournoi

### ISSUE THREAD

**Issue by FalHuor** [StudentGamingNetwork/website#20]
Il faudrait pouvoir ajouter des joueurs remplaçant lors de la création d'une équipe dans la partie tournoi.
Les remplaçants auraient les mêmes prérequis que les joueurs au niveau des informations requises. (certificat étudiant notamment)

Requiert peut être l'ajout d'un système de tags pour différencier les joueurs des remplaçants. (voir des coachs)

Il faudra ensuite pouvoir visualiser les infos des remplaçants sur la page de validation des équipes !

**Comment by hugoattal** [comment]
C'est pas déjà dispo ça 🤔 ?

![image](https://user-images.githubusercontent.com/4563971/137400694-7c6e5c3e-39a5-4e01-a13a-ae1396289186.png)

Ou c'est pas fonctionnel ?
