### ISSUE TITLE
Ajout d'un lien discord sur la page des assos

### ISSUE THREAD

**Issue by FalHuor** [StudentGamingNetwork/website#38]
Ajout d'un attribut discord pour la partie réseau sociaux des associations

- Ajout en Bdd
- Ajout sur la page Admin
- Ajout sur la page publique avec lien + icon si présent 

![image](https://user-images.githubusercontent.com/23261995/208675621-e8f66186-3e55-4080-b1c0-4bc3916aece4.png)

**Comment by FalHuor** [comment]
Petit truc a vérifier, au niveau du code, il n'y a pas d'attribut actuellement (voir website/backend/src/modules/association/model.ts )
![image](https://user-images.githubusercontent.com/23261995/208914142-cf8adb06-e3b1-4bf1-a365-d00aa36077e8.png)

mais une asso à bien un lien vers un discord ainsi que le logo .... (a voir comment et pourquoi !?) 
https://sgnw.fr/association/sigma-gaming

(Aussi les lien affiché entre la page de la fédé et la page de l'asso on l'air différent (les discord n'apparaissent pas sur la page de la fédé)

**Comment by hugoattal** [comment]
C'est chelou ça, y'a bien discord maintenant normalement...

![image](https://user-images.githubusercontent.com/4563971/208918514-40c5dad5-0062-4984-b269-59d21b85a48e.png)

Et c'est bien dans le code: https://github.com/StudentGamingNetwork/website/blob/main/backend/src/modules/association/model.ts#L30

cf https://github.com/StudentGamingNetwork/website/issues/36

T'es sûr que t'as pas oublié de pull 🤔 ?

**Comment by FalHuor** [comment]
J'ai récup le code récemment mais du coup je vais voir le pourquoi du comment. 
Je ferme celle-ci ! 

(Et effectivement en prod je l'ai bien aussi)
