### ISSUE TITLE
Mettre au même niveau les icons des Réseaux sociaux sur la page fédé

### ISSUE THREAD

**Issue by FalHuor** [StudentGamingNetwork/website#42]
Actuellement les icons sont à la suite des autres des éléments directement dans la card, le seul souci c'est que pour une même ligne toute les cards sont à la même taille. 
Ce qui peux rendre le visuel un peu bizarre dans certains cas (voir ci-dessous)
![image](https://user-images.githubusercontent.com/23261995/209091907-fcc6dd50-2f32-4b76-a276-aadb61270a99.png)

**Comment by hugoattal** [comment]
C'est une très bonne first issue, ça se fait très rapidement en utilisant flex 🙂 !

cf https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by FalHuor** [comment]
Y a une ébauche dans la branche link
