### ISSUE TITLE
Droit admin pour le tournoi

### ISSUE THREAD

**Issue by hugoattal** [StudentGamingNetwork/website#59]
Autoriser les membres avec le tag tournoi a
- supprimer une image d'équipe
- changer le nom de l'équipe
- ajouter/éjecter des joueurs (ajouter par email)

**Comment by Kotsudes** [comment]
Je vais attendre la résolution du ticket #58 avant de continuer

**Comment by Kotsudes** [comment]
Je vais également attendre la résolution du ticket #19 avant de continuer (coach et manager)
