### ISSUE TITLE
Autoriser les chiffres dans les slugs

### ISSUE THREAD

**Issue by hugoattal** [StudentGamingNetwork/website#9]
Apparemment, les slugs n'acceptent pas les chiffres. Pas trop de raison à ça il me semble, ça peut faire un bon premier ticket !

![image](https://user-images.githubusercontent.com/4563971/132588359-5f5f0afb-d9f0-4101-b5d0-b697d17b70c5.png)

- La modal pour les assos :
https://github.com/StudentGamingNetwork/website/blob/main/frontend/src/components/template/modals/settings/Association.vue
- Les validators front :
https://github.com/StudentGamingNetwork/website/blob/main/frontend/src/utils/validators.ts
(ça peut être pas mal d'en faire un spécial pour les slugs avec chiffres/lettres/tiret)

Pas de vérification coté backend (c'est juste une string).

![image](https://user-images.githubusercontent.com/4563971/134412539-145b0572-739a-401e-950d-36eebfdf9fb8.png)

**Comment by mathieutu** [comment]
Hello.
Je tombe par hasard sur cette issue via le label `good first issue`. Je fais un cours sur l'OpenSource et comment contribuer avec des élèves de Bachelor 3. Si ça peut attendre quelques semaines, je prendrais bien cette PR en exemple avec les étudiants (il est parfait pour moi, comme premier éxemple pour leur montrer tout le workflow en direct).

Les élèves bosseront ensuite sur des projets opensource, donc si vous avez d'autres issues dans ce genre prochainement, n'hésitez pas à me pinguer!

Merci,
Mathieu.

**Comment by hugoattal** [comment]
Hello @mathieutu

Super idée ! Si en plus certains de vos élèves aimeraient rejoindre le pôle dev du SGN, qu'ils n'hésitent pas !

Je vais améliorer un peu l'issue avec quelques screens et être un peu plus exhaustif sur l'environnement de dev (il faut juste mongodb).

Dis moi si c'est toujours ok pour toi et je te l'assigne.

**Comment by mathieutu** [comment]
> rejoindre le pôle dev du SGN
Et bah cf mon mp sur Twitter!

> je te l'assigne.
Top!

>améliorer un peu l'issue
T'embète pas trop hein, même sans connaître le projet, le code est suffisamment clair pour moi pour pouvoir faire une contrib sans même faire tourner le projet (et là ça sera une démo en live, donc je leur expliquerais). A la limite un ou 2 screens juste pour voir le contexte fonctionnel, ça peut être cool pour eux (parce qu'en vrai j'ai même pas été chercher où était cette modale sur le site 😅).
